[package]
name = "gobject-rs"
version = "0.1.0"
authors = ["黄文俊 <huangwj@goldlokedu.cn>"]

[lib]
name="rust"
crate-type=["staticlib"]

[dependencies]
glib-sys="*"
glib="*"
gobject-sys="*"
gtk-sys="*"
libc="*"

[features]
bindings=[]
